version: '3.9'

services:
  db:
    container_name: db
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - ./db/data:/var/lib/postgresql/data # comment out to run init script every time
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  # db_manager: # only needed for pgadmin
  #   container_name: db_manager
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost.com}
  #     PGADMIN_DEFAULT_USERNAME: ${PGADMIN_DEFAULT_USERNAME:-admin}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #     - ./db/db_manager:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - db
  #   restart: unless-stopped
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: assignment-2-159-352-server
    container_name: assignment-2-159-352-node-server
    command: npm run start
    volumes:
      - /usr/src/app/server/node_modules
    ports:
      - "5555:8000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - db
      - app-network

networks:
  app-network:
    driver: bridge
  db:
    driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local